# Generated by Django 4.2.7 on 2026-02-25 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkrecord',
            name='fat',
        ),
    ]
