# Generated by Django 4.2.7 on 2026-02-25 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_remove_milkrecord_fat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
