# Generated by Django 4.2.7 on 2026-02-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('cow', 'ગાય'), ('buffalo', 'ભેંસ')], max_length=10, verbose_name='પ્રાણી પ્રકાર'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breed',
            field=models.CharField(choices=[('gir', 'ગીર'), ('sahiwal', 'સાહિવાલ'), ('holstein', 'હોલ્સ્ટેન'), ('jersey', 'જર્સી'), ('kankrej', 'કાંકરેજ'), ('murrah', 'મુરાહ'), ('jafarabadi', 'જાફરાબાદી'), ('mehsani', 'મહેસાણી'), ('banni', 'બન્ની')], max_length=20, verbose_name='જાત'),
        ),
    ]
