# Generated by Django 4.2.7 on 2026-02-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_alter_animal_animal_type_alter_animal_breed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='milkrecord',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'દૂધ રેકોર્ડ', 'verbose_name_plural': 'દૂધ રેકોર્ડ્સ'},
        ),
        migrations.AddField(
            model_name='milkrecord',
            name='session',
            field=models.CharField(choices=[('morning', 'સવાર'), ('evening', 'સાંજ')], default='morning', max_length=10, verbose_name='સમય (સવાર/સાંજ)'),
        ),
    ]
