# Generated by Django 4.2.7 on 2026-02-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_alter_milkrecord_options_milkrecord_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='insemination_date',
            field=models.DateField(verbose_name='બીજદાનની તારીખ'),
        ),
    ]
