# Generated by Django 4.2.7 on 2026-03-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_alter_animal_insemination_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ડોક્ટરનું નામ')),
                ('description', models.TextField(verbose_name='વર્ણન')),
                ('contact_number', models.CharField(max_length=15, verbose_name='સંપર્ક નંબર')),
                ('clinic_address', models.TextField(verbose_name='ક્લિનિક સરનામું')),
                ('availability', models.CharField(max_length=100, verbose_name='ઉપલબ્ધતા')),
                ('specialization', models.TextField(verbose_name='વિશેષતા')),
                ('services', models.TextField(verbose_name='સેવાઓ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='doctors/', verbose_name='ફોટો')),
                ('is_active', models.BooleanField(default=True, verbose_name='સક્રિય')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ડોક્ટર',
                'verbose_name_plural': 'ડોક્ટરો',
            },
        ),
    ]
