# Generated by Django 4.2.7 on 2026-03-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='checkup_status',
            field=models.CharField(choices=[('pending', 'બાકી'), ('positive', 'ગર્ભવતી'), ('negative', 'ગર્ભવતી નથી')], default='pending', max_length=10, verbose_name='તપાસ સ્થિતિ'),
        ),
    ]
