# Generated by Django 4.2.7 on 2026-03-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_alter_animal_checkup_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(help_text='બરાબર 10 આંકડાનો મોબાઇલ નંબર', max_length=10, unique=True, verbose_name='મોબાઇલ નંબર'),
        ),
    ]
