# Generated by Django 4.2.7 on 2026-03-03 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
    ]
